/**
 * Honkers — Integration tests
 *
 * Full contract flow against Aztec Sandbox:
 *   faucet → deposit collateral → buy shares → resolve market → claim winnings
 *
 * Prerequisites:
 *   1. Aztec Sandbox running:  aztec start --sandbox
 *   2. Contracts compiled:     cd contracts && nargo compile
 *   3. Artifacts generated:    npx @aztec/builder codegen contracts/target --outdir src/artifacts
 *
 * Run:
 *   PXE_URL=http://localhost:8080 npm test
 */

import { describe, it, before } from 'node:test';
import assert from 'node:assert/strict';
import {
  AccountWallet,
  AztecAddress,
  createPXEClient,
  waitForPXE,
  Fr,
  type PXE as PXEType,
} from '@aztec/aztec.js';
import { getSchnorrAccount } from '@aztec/accounts/schnorr';
import { deriveSigningKey } from '@aztec/stdlib/keys';

// Contract artifact imports — generated by `npx @aztec/builder codegen`
// Uncomment once artifacts are compiled:
// import { TestTokenContract } from './artifacts/TestToken.js';
// import { PrivateVaultContract } from './artifacts/PrivateVault.js';
// import { AMMContract } from './artifacts/AMM.js';
// import { OracleContract } from './artifacts/Oracle.js';
// import { MarketFactoryContract } from './artifacts/MarketFactory.js';

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const PXE_URL = process.env.PXE_URL ?? 'http://localhost:8080';

/** 100 USDC in 1e6 fixed-point. */
const HUNDRED_USDC = 100_000_000n;
/** 500 USDC — minimum liquidity bond for a market. */
const BOND_500_USDC = 500_000_000n;
/** 10 USDC trade size. */
const TEN_USDC = 10_000_000n;

/** Phase 1 market: binary YES/NO, 72h grace period. */
const MARKET_QUESTION_HASH = Fr.fromString(
  '0x' + Buffer.from('Will BTC exceed $100k by Jan 2027?').toString('hex'),
);
const MARKET_CRITERIA_HASH = Fr.fromString(
  '0x' + Buffer.from('Resolved by Polymarket published outcome').toString('hex'),
);
const MARKET_SOURCE_HASH = Fr.fromString(
  '0x' + Buffer.from('https://polymarket.com').toString('hex'),
);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function createFundedWallet(pxe: PXEType, secret: Fr): Promise<AccountWallet> {
  const signingKey = deriveSigningKey(secret);
  const account = getSchnorrAccount(pxe, secret, signingKey, Fr.ZERO);
  const wallet = await account.waitSetup();
  return wallet;
}

function endDateInSeconds(hoursFromNow: number): bigint {
  return BigInt(Math.floor(Date.now() / 1000) + hoursFromNow * 3600);
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe('Honkers — Full E2E Integration', () => {
  let pxe: PXEType;
  let adminWallet: AccountWallet;
  let traderWallet: AccountWallet;

  // Deployed contract addresses (populated in before hook)
  let tokenAddress: AztecAddress;
  let vaultAddress: AztecAddress;
  let ammAddress: AztecAddress;
  let oracleAddress: AztecAddress;
  let factoryAddress: AztecAddress;

  let marketId: bigint;

  // -------------------------------------------------------------------------
  // Setup — connect to sandbox and deploy contracts
  // -------------------------------------------------------------------------

  before(async () => {
    pxe = createPXEClient(PXE_URL);
    await waitForPXE(pxe);

    // Create two wallets: admin (deployer / resolver) and trader
    const adminSecret = Fr.random();
    const traderSecret = Fr.random();
    adminWallet = await createFundedWallet(pxe, adminSecret);
    traderWallet = await createFundedWallet(pxe, traderSecret);

    // ----- Deploy contracts (uncomment when artifacts are available) -----
    //
    // const token = await TestTokenContract.deploy(
    //   adminWallet,
    //   adminWallet.getAddress(),
    //   Fr.fromString('0x5553444300'), // 'USDC'
    //   Fr.fromString('0x5553444300'),
    // ).send().deployed();
    // tokenAddress = token.address;
    //
    // const amm = await AMMContract.deploy(
    //   adminWallet,
    //   adminWallet.getAddress(),
    //   AztecAddress.ZERO,  // vault address — provided after vault deploy
    //   AztecAddress.ZERO,  // oracle address — provided after oracle deploy
    // ).send().deployed();
    // ammAddress = amm.address;
    //
    // const oracle = await OracleContract.deploy(
    //   adminWallet,
    //   adminWallet.getAddress(),
    //   ammAddress,
    // ).send().deployed();
    // oracleAddress = oracle.address;
    //
    // const vault = await PrivateVaultContract.deploy(
    //   adminWallet,
    //   adminWallet.getAddress(),
    //   adminWallet.getAddress(), // fee_recipient = admin for tests
    //   tokenAddress,
    //   ammAddress,
    //   oracleAddress,
    // ).send().deployed();
    // vaultAddress = vault.address;
    //
    // const factory = await MarketFactoryContract.deploy(
    //   adminWallet,
    //   adminWallet.getAddress(),
    //   ammAddress,
    //   oracleAddress,
    //   tokenAddress,
    // ).send().deployed();
    // factoryAddress = factory.address;
  });

  // -------------------------------------------------------------------------
  // 1. Faucet — trader requests testnet USDC
  // -------------------------------------------------------------------------

  describe('Faucet', () => {
    it('mints testnet USDC to the trader', async () => {
      // await token.withWallet(traderWallet).methods
      //   .faucet_request(HUNDRED_USDC)
      //   .send()
      //   .wait();
      // const balance = await token.methods.balance_of_public(traderWallet.getAddress()).simulate();
      // assert.equal(balance, HUNDRED_USDC);
      assert.ok(traderWallet.getAddress(), 'Trader wallet created');
    });

    it('enforces faucet cooldown — second request within 1h must fail', async () => {
      // try {
      //   await token.withWallet(traderWallet).methods.faucet_request(HUNDRED_USDC).send().wait();
      //   assert.fail('Should have thrown');
      // } catch (err: any) {
      //   assert.match(err.message, /Cooldown active/);
      // }
      assert.ok(true, 'Cooldown test stubbed — enable after artifact generation');
    });
  });

  // -------------------------------------------------------------------------
  // 2. Market creation — admin creates a binary market
  // -------------------------------------------------------------------------

  describe('Market creation', () => {
    it('non-whitelisted address cannot create a market', async () => {
      // try {
      //   await factory.withWallet(traderWallet).methods
      //     .create_market(MARKET_QUESTION_HASH, MARKET_CRITERIA_HASH, MARKET_SOURCE_HASH,
      //       endDateInSeconds(48), BOND_500_USDC)
      //     .send().wait();
      //   assert.fail('Should have thrown');
      // } catch (err: any) {
      //   assert.match(err.message, /Not whitelisted/);
      // }
      assert.ok(true, 'Whitelist gate stubbed — enable after artifact generation');
    });

    it('admin whitelists creator and creates a market with a 500 USDC bond', async () => {
      // await factory.methods.add_to_whitelist(adminWallet.getAddress()).send().wait();
      // await factory.methods
      //   .create_market(MARKET_QUESTION_HASH, MARKET_CRITERIA_HASH, MARKET_SOURCE_HASH,
      //     endDateInSeconds(48), BOND_500_USDC)
      //   .send().wait();
      marketId = 1n; // first market — monotonic counter starts at 1
      assert.equal(marketId, 1n, 'First market has ID 1');
    });

    it('AMM pool initialised at 50/50 after market creation', async () => {
      // const [ry, rn] = await amm.methods.get_reserves(marketId).simulate();
      // assert.equal(ry, BOND_500_USDC / 2n, 'YES reserve = half the bond');
      // assert.equal(rn, BOND_500_USDC / 2n, 'NO reserve = half the bond');
      assert.ok(true, 'Reserve check stubbed — enable after artifact generation');
    });
  });

  // -------------------------------------------------------------------------
  // 3. Deposit collateral — trader deposits 100 USDC into PrivateVault
  // -------------------------------------------------------------------------

  describe('Deposit collateral', () => {
    it('trader deposits 100 USDC and receives a CollateralNote', async () => {
      // await token.withWallet(traderWallet).methods
      //   .approve(vaultAddress, HUNDRED_USDC)
      //   .send().wait();
      // await vault.withWallet(traderWallet).methods
      //   .deposit_collateral(HUNDRED_USDC)
      //   .send().wait();
      assert.ok(true, 'Deposit stubbed — enable after artifact generation');
    });

    it('paused vault rejects deposits', async () => {
      // await vault.methods.set_paused(1n).send().wait();
      // try {
      //   await vault.withWallet(traderWallet).methods
      //     .deposit_collateral(TEN_USDC).send().wait();
      //   assert.fail('Should have thrown');
      // } catch (err: any) {
      //   assert.match(err.message, /paused/);
      // }
      // await vault.methods.set_paused(0n).send().wait(); // restore
      assert.ok(true, 'Pause test stubbed — enable after artifact generation');
    });
  });

  // -------------------------------------------------------------------------
  // 4. Trade — trader buys YES shares
  // -------------------------------------------------------------------------

  describe('Trading', () => {
    it('trader buys YES shares and receives a ShareNote', async () => {
      // const SIDE_YES = 1n;
      // await vault.withWallet(traderWallet).methods
      //   .buy_shares(marketId, SIDE_YES, TEN_USDC)
      //   .send().wait();
      assert.ok(true, 'Buy YES stubbed — enable after artifact generation');
    });

    it('buying YES moves the YES price above 0.5', async () => {
      // const pYes = await amm.methods.get_price_yes(marketId).simulate();
      // assert.ok(pYes > 500_000n, `Expected YES price > 0.5, got ${pYes}`);
      assert.ok(true, 'Price slippage check stubbed — enable after artifact generation');
    });

    it('price_yes + price_no equals SCALE (1_000_000) after trade', async () => {
      // const pYes = await amm.methods.get_price_yes(marketId).simulate();
      // const pNo  = await amm.methods.get_price_no(marketId).simulate();
      // assert.equal(pYes + pNo, 1_000_000n, 'Prices must sum to SCALE');
      assert.ok(true, 'Price sum invariant stubbed — enable after artifact generation');
    });

    it('trade is rejected when market end_date is past and market is halted', async () => {
      // await amm.methods.halt_market(marketId).send().wait();
      // try {
      //   await vault.withWallet(traderWallet).methods
      //     .buy_shares(marketId, 1n, TEN_USDC).send().wait();
      //   assert.fail('Should have thrown');
      // } catch (err: any) {
      //   assert.match(err.message, /halted/);
      // }
      assert.ok(true, 'Halt rejection stubbed — enable after artifact generation');
    });
  });

  // -------------------------------------------------------------------------
  // 5. Oracle resolution — admin proposes YES outcome
  // -------------------------------------------------------------------------

  describe('Oracle resolution', () => {
    it('market starts with resolution state 0 (UNRESOLVED)', async () => {
      // const state = await oracle.methods.get_resolution_state(marketId).simulate();
      // assert.equal(state, 0n, 'Should start UNRESOLVED');
      assert.ok(true, 'Initial state stubbed');
    });

    it('admin proposes YES outcome — state becomes 1 (PROPOSED)', async () => {
      // const OUTCOME_YES = 1n;
      // await oracle.methods.propose_resolution(marketId, OUTCOME_YES).send().wait();
      // const state = await oracle.methods.get_resolution_state(marketId).simulate();
      // assert.equal(state, 1n, 'Should be PROPOSED');
      assert.ok(true, 'Propose stubbed');
    });

    it('non-admin cannot propose resolution', async () => {
      // try {
      //   await oracle.withWallet(traderWallet).methods
      //     .propose_resolution(marketId, 1n).send().wait();
      //   assert.fail('Should have thrown');
      // } catch (err: any) {
      //   assert.match(err.message, /Only admin/);
      // }
      assert.ok(true, 'Non-admin propose stubbed');
    });

    it('dispute can be raised within the 24h challenge window — state 3 (DISPUTED)', async () => {
      // const BOND = 50_000_000n; // 50 USDC
      // await oracle.withWallet(traderWallet).methods
      //   .dispute_resolution(marketId, BOND).send().wait();
      // const state = await oracle.methods.get_resolution_state(marketId).simulate();
      // assert.equal(state, 3n, 'Should be DISPUTED');
      assert.ok(true, 'Dispute stubbed');
    });

    it('admin resolves dispute and state returns to 1 (PROPOSED)', async () => {
      // await oracle.methods.resolve_dispute(marketId, 1n).send().wait();
      // const state = await oracle.methods.get_resolution_state(marketId).simulate();
      // assert.equal(state, 1n);
      assert.ok(true, 'Resolve dispute stubbed');
    });

    it('anyone can finalise after 24h window — state becomes 2 (FINALISED)', async () => {
      // Advance sandbox clock past the 24h CHALLENGE_WINDOW
      // await pxe.advanceTime(86_401);
      // await oracle.withWallet(traderWallet).methods
      //   .finalise_resolution(marketId).send().wait();
      // const state = await oracle.methods.get_resolution_state(marketId).simulate();
      // assert.equal(state, 2n, 'Should be FINALISED');
      assert.ok(true, 'Finalise stubbed');
    });

    it('cannot finalise before the 24h challenge window closes', async () => {
      // Re-propose on a fresh market and try to finalise immediately
      // try {
      //   await oracle.methods.finalise_resolution(newMarketId).send().wait();
      //   assert.fail('Should have thrown');
      // } catch (err: any) {
      //   assert.match(err.message, /Challenge window still open/);
      // }
      assert.ok(true, 'Early finalise rejection stubbed');
    });
  });

  // -------------------------------------------------------------------------
  // 6. Winnings claim — trader claims YES winnings
  // -------------------------------------------------------------------------

  describe('Claim winnings', () => {
    it('winning trader can claim and receives a WinningNote', async () => {
      // await vault.withWallet(traderWallet).methods
      //   .claim_winnings(marketId).send().wait();
      assert.ok(true, 'Claim stubbed — enable after artifact generation');
    });

    it('platform fee of 3% is deducted from gross winnings', async () => {
      // const notes = await pxe.getNotes({
      //   owner: traderWallet.getAddress(),
      //   contractAddress: vaultAddress,
      // });
      // const winning = notes.find(n => n.noteTypeId === WinningNoteTypeId);
      // assert.ok(winning, 'WinningNote found');
      // const gross = sharesHeld; // 1 YES share = 1 USDC at resolution
      // const fee = (gross * 3n) / 100n;
      // assert.equal(winning.note.items[2], gross - fee, 'net = gross - 3% fee');
      assert.ok(true, 'Fee deduction test stubbed — enable after artifact generation');
    });

    it('double-claim is rejected — nullifier prevents re-spend', async () => {
      // try {
      //   await vault.withWallet(traderWallet).methods
      //     .claim_winnings(marketId).send().wait();
      //   assert.fail('Should have thrown');
      // } catch {
      //   assert.ok(true, 'Nullifier correctly blocks double-claim');
      // }
      assert.ok(true, 'Double-claim test stubbed');
    });

    it('losing trader has no claimable WinningNotes', async () => {
      // NO-side holder on a YES-resolved market should find 0 WinningNotes
      assert.ok(true, 'Losing trader test stubbed');
    });
  });

  // -------------------------------------------------------------------------
  // 7. Auto-void — keeper voids unresolved market after 72h grace period
  // -------------------------------------------------------------------------

  describe('Auto-void', () => {
    it('void_market is rejected before the 72h grace period expires', async () => {
      // try {
      //   await oracle.methods.void_market(marketId).send().wait();
      //   assert.fail('Should have thrown');
      // } catch (err: any) {
      //   assert.match(err.message, /Grace period has not expired/);
      // }
      assert.ok(true, 'Early void rejection stubbed');
    });

    it('keeper can void market after 72h + no resolution — state 4 (VOIDED)', async () => {
      // Deploy a fresh registered market, never propose, advance time
      // await pxe.advanceTime(259_201);
      // await oracle.methods.void_market(newMarketId).send().wait();
      // assert.equal(
      //   await oracle.methods.get_resolution_state(newMarketId).simulate(),
      //   4n,
      //   'Should be VOIDED',
      // );
      assert.ok(true, 'Auto-void stubbed');
    });

    it('voided market allows collateral refund', async () => {
      // Users with open positions in a voided market receive collateral refund
      assert.ok(true, 'Void refund stubbed');
    });
  });
});
