
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import AMMContractArtifactJson from '../../../../contracts/target/amm-AMM.json' with { type: 'json' };
export const AMMContractArtifact = loadContractArtifact(AMMContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract AMM;
 */
export class AMMContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, AMMContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): AMMContract {
    return Contract.at(address, AMMContract.artifact, wallet) as AMMContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<AMMContract>(PublicKeys.default(), wallet, AMMContractArtifact, (instance, wallet) => AMMContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<AMMContract>(publicKeys, wallet, AMMContractArtifact, (instance, wallet) => AMMContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof AMMContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<AMMContract['methods'][M]>
  ) {
    return new DeployMethod<AMMContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      AMMContractArtifact,
      (instance, wallet) => AMMContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return AMMContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(AMMContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'vault' | 'oracle' | 'deps_set' | 'reserve_yes' | 'reserve_no' | 'invariant_k' | 'end_dates' | 'halted'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
vault: {
      slot: new Fr(2n),
    },
oracle: {
      slot: new Fr(3n),
    },
deps_set: {
      slot: new Fr(4n),
    },
reserve_yes: {
      slot: new Fr(5n),
    },
reserve_no: {
      slot: new Fr(6n),
    },
invariant_k: {
      slot: new Fr(7n),
    },
end_dates: {
      slot: new Fr(8n),
    },
halted: {
      slot: new Fr(9n),
    }
      } as ContractStorageLayout<'admin' | 'vault' | 'oracle' | 'deps_set' | 'reserve_yes' | 'reserve_no' | 'invariant_k' | 'end_dates' | 'halted'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_price_no(market_id: field) */
    get_price_no: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_price_yes(market_id: field) */
    get_price_yes: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_reserves(market_id: field) */
    get_reserves: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** halt_market(market_id: field) */
    halt_market: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize_market(market_id: field, initial_liquidity: field, end_date: field) */
    initialize_market: ((market_id: FieldLike, initial_liquidity: FieldLike, end_date: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_halted(market_id: field) */
    is_halted: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_dependencies(vault: struct, oracle: struct) */
    set_dependencies: ((vault: AztecAddressLike, oracle: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** swap(market_id: field, side: field, amount_in: field) */
    swap: ((market_id: FieldLike, side: FieldLike, amount_in: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
