
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MarketFactoryContractArtifactJson from '../../../../contracts/target/market_factory-MarketFactory.json' with { type: 'json' };
export const MarketFactoryContractArtifact = loadContractArtifact(MarketFactoryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MarketFactory;
 */
export class MarketFactoryContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MarketFactoryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MarketFactoryContract {
    return Contract.at(address, MarketFactoryContract.artifact, wallet) as MarketFactoryContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<MarketFactoryContract>(PublicKeys.default(), wallet, MarketFactoryContractArtifact, (instance, wallet) => MarketFactoryContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<MarketFactoryContract>(publicKeys, wallet, MarketFactoryContractArtifact, (instance, wallet) => MarketFactoryContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MarketFactoryContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MarketFactoryContract['methods'][M]>
  ) {
    return new DeployMethod<MarketFactoryContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MarketFactoryContractArtifact,
      (instance, wallet) => MarketFactoryContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MarketFactoryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MarketFactoryContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'amm' | 'oracle' | 'token' | 'deps_set' | 'next_market_id' | 'whitelist' | 'market_question_hash' | 'market_criteria_hash' | 'market_source_hash' | 'market_creator' | 'market_end_date' | 'market_bond'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
amm: {
      slot: new Fr(2n),
    },
oracle: {
      slot: new Fr(3n),
    },
token: {
      slot: new Fr(4n),
    },
deps_set: {
      slot: new Fr(5n),
    },
next_market_id: {
      slot: new Fr(6n),
    },
whitelist: {
      slot: new Fr(7n),
    },
market_question_hash: {
      slot: new Fr(8n),
    },
market_criteria_hash: {
      slot: new Fr(9n),
    },
market_source_hash: {
      slot: new Fr(10n),
    },
market_creator: {
      slot: new Fr(11n),
    },
market_end_date: {
      slot: new Fr(12n),
    },
market_bond: {
      slot: new Fr(13n),
    }
      } as ContractStorageLayout<'admin' | 'amm' | 'oracle' | 'token' | 'deps_set' | 'next_market_id' | 'whitelist' | 'market_question_hash' | 'market_criteria_hash' | 'market_source_hash' | 'market_creator' | 'market_end_date' | 'market_bond'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_to_whitelist(creator: struct) */
    add_to_whitelist: ((creator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_market(question_hash: field, criteria_hash: field, source_hash: field, end_date: field, bond_amount: field) */
    create_market: ((question_hash: FieldLike, criteria_hash: FieldLike, source_hash: FieldLike, end_date: FieldLike, bond_amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_market_info(market_id: field) */
    get_market_info: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_next_market_id() */
    get_next_market_id: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_whitelisted(creator: struct) */
    is_whitelisted: ((creator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** remove_from_whitelist(creator: struct) */
    remove_from_whitelist: ((creator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_dependencies(amm: struct, oracle: struct, token: struct) */
    set_dependencies: ((amm: AztecAddressLike, oracle: AztecAddressLike, token: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
