
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import OracleContractArtifactJson from '../../../../contracts/target/oracle-Oracle.json' with { type: 'json' };
export const OracleContractArtifact = loadContractArtifact(OracleContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Oracle;
 */
export class OracleContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, OracleContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): OracleContract {
    return Contract.at(address, OracleContract.artifact, wallet) as OracleContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<OracleContract>(PublicKeys.default(), wallet, OracleContractArtifact, (instance, wallet) => OracleContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<OracleContract>(publicKeys, wallet, OracleContractArtifact, (instance, wallet) => OracleContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof OracleContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<OracleContract['methods'][M]>
  ) {
    return new DeployMethod<OracleContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      OracleContractArtifact,
      (instance, wallet) => OracleContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return OracleContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(OracleContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'amm' | 'deps_set' | 'resolution_state' | 'proposed_outcome' | 'proposed_at' | 'end_dates' | 'dispute_bond' | 'disputer'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
amm: {
      slot: new Fr(2n),
    },
deps_set: {
      slot: new Fr(3n),
    },
resolution_state: {
      slot: new Fr(4n),
    },
proposed_outcome: {
      slot: new Fr(5n),
    },
proposed_at: {
      slot: new Fr(6n),
    },
end_dates: {
      slot: new Fr(7n),
    },
dispute_bond: {
      slot: new Fr(8n),
    },
disputer: {
      slot: new Fr(9n),
    }
      } as ContractStorageLayout<'admin' | 'amm' | 'deps_set' | 'resolution_state' | 'proposed_outcome' | 'proposed_at' | 'end_dates' | 'dispute_bond' | 'disputer'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** challenge_seconds_remaining(market_id: field, current_timestamp: field) */
    challenge_seconds_remaining: ((market_id: FieldLike, current_timestamp: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** dispute_resolution(market_id: field, bond_amount: field) */
    dispute_resolution: ((market_id: FieldLike, bond_amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** finalise_resolution(market_id: field) */
    finalise_resolution: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_dispute_info(market_id: field) */
    get_dispute_info: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_end_date(market_id: field) */
    get_end_date: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposed_at(market_id: field) */
    get_proposed_at: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposed_outcome(market_id: field) */
    get_proposed_outcome: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_resolution_state(market_id: field) */
    get_resolution_state: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_void_eligible(market_id: field, current_timestamp: field) */
    is_void_eligible: ((market_id: FieldLike, current_timestamp: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** propose_resolution(market_id: field, outcome: field) */
    propose_resolution: ((market_id: FieldLike, outcome: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_market(market_id: field, end_date: field) */
    register_market: ((market_id: FieldLike, end_date: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** resolve_dispute(market_id: field, new_outcome: field) */
    resolve_dispute: ((market_id: FieldLike, new_outcome: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_dependencies(amm: struct) */
    set_dependencies: ((amm: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** void_market(market_id: field) */
    void_market: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
