
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import PrivateVaultContractArtifactJson from '../contracts/target/private_vault-PrivateVault.json' with { type: 'json' };
export const PrivateVaultContractArtifact = loadContractArtifact(PrivateVaultContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract PrivateVault;
 */
export class PrivateVaultContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, PrivateVaultContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PrivateVaultContract {
    return Contract.at(address, PrivateVaultContract.artifact, wallet) as PrivateVaultContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, fee_recipient: AztecAddressLike) {
    return new DeployMethod<PrivateVaultContract>(PublicKeys.default(), wallet, PrivateVaultContractArtifact, (instance, wallet) => PrivateVaultContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, fee_recipient: AztecAddressLike) {
    return new DeployMethod<PrivateVaultContract>(publicKeys, wallet, PrivateVaultContractArtifact, (instance, wallet) => PrivateVaultContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PrivateVaultContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PrivateVaultContract['methods'][M]>
  ) {
    return new DeployMethod<PrivateVaultContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PrivateVaultContractArtifact,
      (instance, wallet) => PrivateVaultContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PrivateVaultContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PrivateVaultContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'fee_recipient' | 'token' | 'amm' | 'oracle' | 'paused' | 'collateral' | 'shares' | 'winnings'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
fee_recipient: {
      slot: new Fr(2n),
    },
token: {
      slot: new Fr(4n),
    },
amm: {
      slot: new Fr(6n),
    },
oracle: {
      slot: new Fr(8n),
    },
paused: {
      slot: new Fr(10n),
    },
collateral: {
      slot: new Fr(11n),
    },
shares: {
      slot: new Fr(12n),
    },
winnings: {
      slot: new Fr(13n),
    }
      } as ContractStorageLayout<'admin' | 'fee_recipient' | 'token' | 'amm' | 'oracle' | 'paused' | 'collateral' | 'shares' | 'winnings'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** _verify_swap(market_id: field, side: field, collateral_amount: field, min_shares_out: field) */
    _verify_swap: ((market_id: FieldLike, side: FieldLike, collateral_amount: FieldLike, min_shares_out: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** buy_shares(market_id: field, side: field, collateral_amount: field, min_shares_out: field, price_per_share: field) */
    buy_shares: ((market_id: FieldLike, side: FieldLike, collateral_amount: FieldLike, min_shares_out: FieldLike, price_per_share: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_winnings(market_id: field) */
    claim_winnings: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct, fee_recipient: struct) */
    constructor: ((admin: AztecAddressLike, fee_recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deposit_collateral(amount: field) */
    deposit_collateral: ((amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** emergency_pause() */
    emergency_pause: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_paused() */
    is_paused: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** refund_void_market(market_id: field) */
    refund_void_market: ((market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_dependencies(token: struct, amm: struct, oracle: struct) */
    set_dependencies: ((token: AztecAddressLike, amm: AztecAddressLike, oracle: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** settle_winnings(market_id: field, winning_side: field, block_number: field) */
    settle_winnings: ((market_id: FieldLike, winning_side: FieldLike, block_number: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unpause() */
    unpause: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw_collateral(amount: field) */
    withdraw_collateral: ((amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
