
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import TestTokenContractArtifactJson from '../contracts/target/test_token-TestToken.json' with { type: 'json' };
export const TestTokenContractArtifact = loadContractArtifact(TestTokenContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract TestToken;
 */
export class TestTokenContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, TestTokenContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): TestTokenContract {
    return Contract.at(address, TestTokenContract.artifact, wallet) as TestTokenContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, name: FieldLike, symbol: FieldLike) {
    return new DeployMethod<TestTokenContract>(PublicKeys.default(), wallet, TestTokenContractArtifact, (instance, wallet) => TestTokenContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, name: FieldLike, symbol: FieldLike) {
    return new DeployMethod<TestTokenContract>(publicKeys, wallet, TestTokenContractArtifact, (instance, wallet) => TestTokenContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof TestTokenContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<TestTokenContract['methods'][M]>
  ) {
    return new DeployMethod<TestTokenContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      TestTokenContractArtifact,
      (instance, wallet) => TestTokenContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return TestTokenContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(TestTokenContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'name' | 'symbol' | 'decimals' | 'total_supply' | 'balances' | 'last_faucet'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
name: {
      slot: new Fr(2n),
    },
symbol: {
      slot: new Fr(4n),
    },
decimals: {
      slot: new Fr(6n),
    },
total_supply: {
      slot: new Fr(8n),
    },
balances: {
      slot: new Fr(9n),
    },
last_faucet: {
      slot: new Fr(10n),
    }
      } as ContractStorageLayout<'admin' | 'name' | 'symbol' | 'decimals' | 'total_supply' | 'balances' | 'last_faucet'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** admin_mint(to: struct, amount: field) */
    admin_mint: ((to: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** balance_of(owner: struct) */
    balance_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct, name: field, symbol: field) */
    constructor: ((admin: AztecAddressLike, name: FieldLike, symbol: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** faucet(amount: field) */
    faucet: ((amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_decimals() */
    get_decimals: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_name() */
    get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_symbol() */
    get_symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** last_faucet_time(owner: struct) */
    last_faucet_time: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** total_supply() */
    total_supply: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_public(to: struct, amount: field) */
    transfer_public: ((to: AztecAddressLike, amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
